workflows:
  ios:
    name: iOS build
    platform: ios
    script:
      # Шаг 1: Установка рабочих нагрузок .NET MAUI
      - echo "Installing .NET MAUI workloads..."
      - dotnet workload restore
      # Шаг 2: Восстановление зависимостей
      - echo "Restoring dependencies..."
      - dotnet restore YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj
      # Шаг 3: Сборка проекта
      - echo "Building iOS project..."
      - dotnet build YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj --configuration Release
    # Шаг 4: Артефакты, которые нужно сохранить после сборки
    artifacts:
      - build/ios/**/*.app
    # Шаг 5: Публикация
    publishing:
      email:
        on_failure: true
        on_success: true
        to: 'illiarchuk@gmail.com'
