workflows:
  ios:
    name: iOS build
    steps:
      - name: "Install .NET workloads"
        run:
          - dotnet workload install maui-ios
          - dotnet workload install maui-tizen
          - dotnet workload restore

      - name: "Restore dependencies"
        run:
          - dotnet restore YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj

      - name: "Build iOS project"
        run:
          - dotnet build YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj --configuration Release

    artifacts:
      - build/ios/**/*.app
