workflows:
  ios-build:
    name: iOS build
    scripts:
      - name: Install .NET SDK
        script: |
          # Устанавливаем зависимости для Ubuntu/Debian
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          # Добавляем ключ для репозитория Microsoft
          wget https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          # Добавляем репозиторий Microsoft
          sudo add-apt-repository https://packages.microsoft.com/ubuntu/20.04/prod
          sudo apt-get update
          # Устанавливаем .NET SDK
          sudo apt-get install -y dotnet-sdk-8.0

      - name: Verify .NET SDK installation
        script: |
          # Проверяем установку .NET SDK
          dotnet --version

      - name: Install .NET workloads
        script: |
          dotnet workload install maui-ios
          dotnet workload install maui-tizen
          dotnet workload restore

      - name: Restore dependencies
        script: dotnet restore YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj

      - name: Build iOS project
        script: dotnet build YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj --configuration Release

    artifacts:
      - build/ios/**/*.app
