workflows:
  ios-build:
    name: iOS Build
    source:
      type: git
      url: https://github.com/illiarchuk/YaNeSosalAloox
    build:
      ios:
        version: 8.0
        script:
          - echo "Installing .NET workloads..."
          - dotnet workload install maui-ios
          - dotnet workload install maui-tizen
          - dotnet workload restore
          - echo "Restoring dependencies..."
          - dotnet restore YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj
          - echo "Building iOS project..."
          - dotnet build YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj --configuration Release
    artifacts:
      - build/ios/**/*.app
