workflows:
  ios-build:
    name: iOS build
    scripts:
      - name: Install .NET SDK (macOS)
        script: |
          # Устанавливаем Homebrew, если он еще не установлен
          if ! command -v brew &>/dev/null; then
            echo "Homebrew not found. Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          # Устанавливаем .NET SDK через Homebrew
          brew install --cask dotnet-sdk
          export PATH="$HOME/.dotnet:$PATH"

      - name: Verify .NET SDK installation
        script: |
          # Проверяем установку .NET SDK
          dotnet --version

      - name: Install .NET workloads
        script: |
          sudo DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 dotnet workload install maui-ios --disable-parallel
          sudo DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 dotnet workload install maui-tizen --disable-parallel
          sudo DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 dotnet workload restore

      - name: Restore dependencies
        script: dotnet restore YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj

      - name: Build iOS project
        script: dotnet build YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj --configuration Release

    artifacts:
      - build/ios/**/*.app
ЫЫ