workflows:
  ios-build:
    name: iOS build
    triggers:
      - push:
          branches:
            - main
    steps:
      - name: Установка .NET workloads
        run: |
          echo "Installing .NET workloads..."
          dotnet workload install maui-ios
          dotnet workload install maui-tizen
          dotnet workload restore
          
      - name: Восстановление зависимостей
        run: |
          echo "Restoring dependencies..."
          dotnet restore YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj
          
      - name: Построение iOS проекта
        run: |
          echo "Building iOS project..."
          dotnet build YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj --configuration Release
          
    artifacts:
      - build/ios/**/*.app
