workflows:
  ios:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        DOTNET_VERSION: 8.0.100
    scripts:
      - name: Установка .NET SDK
        script: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $DOTNET_VERSION
          echo 'export DOTNET_ROOT=$HOME/.dotnet' >> $HOME/.bashrc
          echo 'export PATH=$HOME/.dotnet:$HOME/.dotnet/tools:$PATH' >> $HOME/.bashrc
          source $HOME/.bashrc
      - name: Проверка версии .NET
        script: $HOME/.dotnet/dotnet --version
      - name: Восстановление зависимостей
        script: $HOME/.dotnet/dotnet restore YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj
      - name: Сборка проекта
        script: $HOME/.dotnet/dotnet build YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj --configuration Release
    artifacts:
      - build/ios/**/*.ipa
    publishing:
      email:
        recipients:
          - "illiarchuk@gmail.com"  # Замени на свою почту
