workflows:
  ios:
    name: iOS build
    steps:
      - run:
          name: Installing .NET workloads
          command: |
            dotnet workload install maui-ios
            dotnet workload install maui-tizen
            dotnet workload restore
      - run:
          name: Restoring dependencies
          command: |
            dotnet restore YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj
      - run:
          name: Building iOS project
          command: |
            dotnet build YaNeSosalAloo.iOS/YaNeSosalAloo.iOS.csproj --configuration Release
    artifacts:
      - build/ios/**/*.app
